# Generated by Django 5.1 on 2024-08-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
